### ISSUE TITLE
Other Email Addresses

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/CloudAppSecurityDocs#125]
Is there a way to get all Alerts (Low, Med, High) sent to another email address besides the admins'? I haven't found any other place in the Cloud App Security portal to set up something like this. Its maddening because we react to all of our alerts from other sources in a shared mailbox, but short of a forwarding rule we can't seem to find a way to do the same here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 618d6ba3-6340-f3d9-3d88-474dfa911d9b
* Version Independent ID: ccfecd9f-43ab-4f1d-92b5-b26e1e2b3b80
* Content: [Set admin preferences - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/admin-settings)
* Content Source: [CloudAppSecurityDocs/admin-settings.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/admin-settings.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @pyoungberg , thanks for reaching out. There isn't a setting to email all alerts, but when you create a policy, under Alerts, you can set the **Send alert as email** setting to your shared inbox and then use the **Save these settings as the default for your organization** so that all policies will share this setting. For more information, see https://docs.microsoft.com/cloud-app-security/control-cloud-apps-with-policies.
HTH, Rachel

**Comment by rkarlin** [comment]
#please-close

**Comment by pyoungberg** [comment]
My hero, thanks @rkarlin this is a big win for us.
