### ISSUE TITLE
Error in starting container

### ISSUE THREAD

**Issue by EliWallic** [MicrosoftDocs/CloudAppSecurityDocs#130]
Hi all,

I am getting an error if I try to start the container as described in the docs:

Error response from daemon: driver failed programming external connectivity on endpoint <NAME>: Error starting userland proxy: Bind for 0.0.0.0:21 unexpected error Permissions denied.

Running on Windows 10 Pro behind a proxy which is also given in the command at the part "PROXY=ip:port"

**Comment by ShlomoSagir-MS** [comment]
@EliWallic  Thanks for your question.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. You may find a solution to your issue in the [Troubleshooting Cloud Discovery](https://go.microsoft.com/fwlink/?linkid=2100542) topic, otherwise, to make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
