### ISSUE TITLE
Bug in execution but documentation looks correct

### ISSUE THREAD

**Issue by sdiver78** [MicrosoftDocs/CloudAppSecurityDocs#133]
Bug in execution but documentation looks correct. In reference to https://docs.microsoft.com/en-us/cloud-app-security/troubleshoot-docker at step 4. 

In a terminal run: docker exec -t <collector name> update_certs. The command should produce a similar output to what's seen in the following screenshot. Documentation is correct but script execution has a bug. 

Actual output from this command: 
rsyslog: stopped
rsyslog: started
ftp: ERROR (no such process)
ftp: ERROR (no such process) 

Have to manually connect to docker and do a service restart on ftpd, not ftp as script attempts to do and as the documentation shows.

**Comment by ShlomoSagir-MS** [comment]
@sdiver78 Thanks for your question. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. You may find a solution to your issue in the [Troubleshooting Cloud Discovery](https://go.microsoft.com/fwlink/?linkid=2100542) topic, otherwise, to make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Note:** The topic was recently updated and the [URL has changed](https://docs.microsoft.com/en-us/cloud-app-security/log-collector-ftp).
