### ISSUE TITLE
System alert: Cloud Discovery automatic log upload error

### ISSUE THREAD

**Issue by devi1dude** [MicrosoftDocs/CloudAppSecurityDocs#138]
Hi,
I can't seem to find any fix for this. 

The Cloud Discovery log collector Cloud App Security Proxy has not uploaded logs from data source ADALLOM_PROXY_RAW_TRAFFIC for 48 hours.
Verify that logs are being sent from your on-premises data sources to the log collector.

**Comment by ShlomoSagir-MS** [comment]
@devi1dude Thanks for your question.
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. You may find a solution to your issue in the [Troubleshooting Cloud Discovery](https://go.microsoft.com/fwlink/?linkid=2100542) topic, otherwise, to make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
