### ISSUE TITLE
Dashboard table contains old dashboard names?

### ISSUE THREAD

**Issue by jpr2016git** [MicrosoftDocs/CloudAppSecurityDocs#140]
It appears that some of the names of the dashboards in the table are not current. At least I don't see "Insights" in the CAS portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bfee6e2-2879-2e43-0a8a-d3167762d6ee
* Version Independent ID: f5f6ae9a-b605-dc4d-7be6-335f47e101d5
* Content: [Investigate cloud app risks & suspicious activity - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/investigate#feedback)
* Content Source: [CloudAppSecurityDocs/investigate.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/investigate.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@jpr2016git  Thanks for your feedback. After investigating, we've discovered that app dashboards are displayed in context to the app, meaning that you do not see all dashboards for every app. For example, the Box app does show the **Insights** dashboard. Since the table is correct, we will not change the topic at this time, though we will look into making it clearer when it is next updated. Thanks again; we always appreciate feedback on our documentation!
