### ISSUE TITLE
SIEM Agent Location Preference

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/CloudAppSecurityDocs#149]
Can the document identify whether on-premises or Azure would be the preferred location for this agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0f3293-02dc-6fc0-9003-eaf932cbe9ff
* Version Independent ID: ee2bccc6-e9b9-ad81-1d4d-a6667ebfc839
* Content: [SIEM integration with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/siem)
* Content Source: [CloudAppSecurityDocs/siem.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/siem.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@Mark7even  Thanks for the suggestion. At this time, we cannot modify the page as you describe for the following reasons:

- we choose not to offer product preferences as they depend on each organizations specific scenario.

Because we cannot change the referenced page to include the information  that you're asking for, I am closing this issue. However, we always appreciate feedback on our documentation.
