### ISSUE TITLE
License required for Cloudapp security

### ISSUE THREAD

**Issue by BharathiAN** [MicrosoftDocs/CloudAppSecurityDocs#151]
Whether all users should have E5 license or only admins having E5 license is enough for using this cloud app security. Pl clarify

**Comment by ShlomoSagir-MS** [comment]
@BharathiAN  It looks like you have a question about the product itself, rather than an issue with the documentation. Here are a few options that might help you with the issue you are experiencing:

- Review the [licensing datasheet](https://aka.ms/mcaslicensing).
- Submit your issue using the instructions in the [Support and troubleshooting](https://go.microsoft.com/fwlink/?linkid=2099672) guide.
