### ISSUE TITLE
List all supported file types

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/CloudAppSecurityDocs#156]
"Cloud App Security's built in DLP engines perform content inspection by extracting text from all common file types (100+) including Office, Open Office, compressed files, various rich text formats, XML, HTML, and more"

Can this be stated what all the 100+ are? or a link be given to where that information is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0d4ad8-405a-a300-08e8-f0c02ab1feb4
* Version Independent ID: cfa88e4b-a518-9471-a21f-70048655dbb2
* Content: [Monitor and protect files in cloud apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/data-protection-policies#feedback)
* Content Source: [CloudAppSecurityDocs/data-protection-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/data-protection-policies.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@Mark7even Thanks for the suggestion; at this time, we cannot modify the page as you describe for the following reasons:
-	It's dynamic list that constantly changes and because of the frequency in which we update the page, it's not feasible to manually modify it to provide the additional information that you seek.

Because we cannot change the referenced page to include the information and functionality that you're asking for, I am closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.

**Comment by Mark7even** [comment]
That's ridiculous. How are you supposed to explain to an enterprise on what is supported and what is not? Is there somewhere else in the docs that this information exists?
