### ISSUE TITLE
Can't integrate AIP in Cloud App Security

### ISSUE THREAD

**Issue by phamanh1652** [MicrosoftDocs/CloudAppSecurityDocs#159]
Hello, I'm using trial of Office 365 E5. I make labels in AIP and want to integrate in CAS to manually apply labels for files. But I can't do that. This is my configuration and status. [Integrate AIP in CAS.docx](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/files/3509334/Integrate.AIP.in.CAS.docx)

**Comment by ShlomoSagir-MS** [comment]
@phamanh1652 
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. You may find a solution to your issue in the [Azure Information Protection integration](https://go.microsoft.com/fwlink/?linkid=2101421) topic, otherwise, to make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
