### ISSUE TITLE
Managed domains

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/CloudAppSecurityDocs#169]
Hello,
For Managed domains, should we add only the one added to tenant, or also should add with ".onmicrosoft.com"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47cc4f8f-f7d2-07ce-4fb2-4e87eef26655
* Version Independent ID: 33d5a394-9e8b-2db5-6a8b-ec6219463b30
* Content: [Set up your organization's settings in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/general-setup)
* Content Source: [CloudAppSecurityDocs/general-setup.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/general-setup.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@lightupdifire Thanks for your question. I'm investigating and will get back to you.

**Comment by shsagir** [comment]
@lightupdifire After investigating the question, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

However, the following information I received from support may be helpful to you:

> If this is a demo tenant, the “onmicrosoft.com“ should be added automatically to the managed domains. Otherwise, add all the domains that he considered to be trusted/internal.

If you need any further assistance, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672). But, thanks again; we always appreciate feedback on our documentation!
