### ISSUE TITLE
Missing option for 'access policies'

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/CloudAppSecurityDocs#186]
In step 2, "In the Policies page, click Create policy and select Access policy", there is no option in our portal for "Access policy". Currently only "App discovery policy" shows. 
Is there a different way to get to these policies? 
Or perhaps there are some other pre-requites that have not been described on this page?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e0921d-c905-8f46-403d-2e05e9645cb8
* Version Independent ID: af25066d-94c9-923d-0f65-36d834adcbc0
* Content: [Create Cloud App Security access policies to allow and block access](https://docs.microsoft.com/en-gb/cloud-app-security/access-policy-aad#feedback)
* Content Source: [CloudAppSecurityDocs/access-policy-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/access-policy-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for contacting Microsoft about your issue.

In order to see this option, you must have the following prerequisites mentioned in the topic:

- Azure AD Premium P1 license
- The relevant apps should be [deployed with Conditional Access App Control](https://docs.microsoft.com/en-gb/cloud-app-security/proxy-deployment-aad)
- An [Azure AD conditional access policy](https://docs.microsoft.com/azure/active-directory/active-directory-conditional-access-azure-portal) should be in place that redirects users to Microsoft Cloud App Sec

If you are still having an issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) who will be able to help you. If support determines that there are additional requirements, please reopen this issue with @mention and provide the details of the additional requirements.
