### ISSUE TITLE
Missing link to API documentation

### ISSUE THREAD

**Issue by nromyn** [MicrosoftDocs/CloudAppSecurityDocs#194]
The top of the page has this:
&gt; To see the full documentation of the API, in the Cloud App Security portal go to Help &gt; API documentation.

Considering this is the official documentation for Cloud App Security (and in fact all of Microsoft Documentation) the API documentation should be located here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49f4498-7b65-28f7-f31d-c7a21149025e
* Version Independent ID: d93e55ac-bec8-5aba-5cba-923cee400542
* Content: [API token management in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/api-tokens#feedback)
* Content Source: [CloudAppSecurityDocs/api-tokens.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-tokens.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@nromyn Thanks for your feedback. After investigating, we've discovered that currently the API docs are not public and as such are only available in the manner described in the topic. However, you're suggestion is valid and is something we are considering for the future.

Because we cannot change the referenced page to include the information and functionality that you're asking for at this time, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
