### ISSUE TITLE
Missing Alert Category information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#198]
there is nothing on this page that discusses the Alert Category filter. Please provide some explanation about which alert type is assigned to each Category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70912b42-016b-d311-86cd-86f2e5e04a51
* Version Independent ID: 1744f30c-af16-cf4a-6a91-043e6f92b330
* Content: [Manage alerts raised in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/managing-alerts)
* Content Source: [CloudAppSecurityDocs/managing-alerts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/managing-alerts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@name Thanks for your feedback. After investigating, we've discovered the categories is simple a grouping/filtering label and has no bearing on policy behavior or any direct relationship to an alert type. You can assign them in policies as is meaningful to you and as such doesn't require the documentation you requested. But, thanks again; we always appreciate feedback on our documentation.

Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
