### ISSUE TITLE
Number of 'Policy types'

### ISSUE THREAD

**Issue by rynatori** [MicrosoftDocs/CloudAppSecurityDocs#218]
Now we can see three more policy types on CAS console.
-Malware detection policy
-OAuth app anomaly detection policy
-OAuth app policy
Would you mind if you added them to this page?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465291ec-a6ff-9446-1a30-89cfc05d2e74
* Version Independent ID: 28256a68-04c7-81d4-054d-711264c9e5e1
* Content: [Control cloud app usage by creating policies - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/control-cloud-apps-with-policies#feedback)
* Content Source: [CloudAppSecurityDocs/control-cloud-apps-with-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/control-cloud-apps-with-policies.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@rynatori Thanks for your feedback. Information regarding specific policies can be found on their respective pages, as follows:

- [Malware detection](https://docs.microsoft.com/cloud-app-security/anomaly-detection-policy#malware-detection)
- [OAuth app anomalies](https://docs.microsoft.com/en-us/cloud-app-security/app-permission-policy#oauth-app-anomaly-detection-policies)

Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
