### ISSUE TITLE
Conditional Access App Control "Block Downloads" does not block jpg download

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/CloudAppSecurityDocs#225]
Hello,

Conditional Access App Control "Block Downloads" does not block files with the ".jpg" extension download. I also tried to create a Session Control policy in MCAS to block jpg download but it does not work either.
You can block jpg upload but not download.

**Comment by shsagir** [comment]
@Martony78 Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

I'll check with the product team though it could take from a few business days to a few weeks to look further into your issue. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by Martony78** [comment]
Hello,

As I can see png files are also concerned... it seems like image files are the issue. The problem is if we rename any file to jpg or png we can download it from any browser.

**Comment by shsagir** [comment]
@Martony78 I discussed the issue with the product team and since the problem is with the product itself and not with the product documentation, they requested that you email casfeedback@microsoft.com where you can get further assistance on this issue. In the meantime, I'm closing this issue. Thanks again for your feedback.
