### ISSUE TITLE
Include File max side for file labeling, as well as max number of labels

### ISSUE THREAD

**Issue by gesmith-Ms** [MicrosoftDocs/CloudAppSecurityDocs#231]
We need to include that the max size for a file is 50MB here (it states there is a max size, but doesn't say what it is), as well as the max number of applies for an application is 100 per day.  this is crucial information that should be added here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3dc78f-a44c-de54-2a66-3f830345a90d
* Version Independent ID: fdc60175-126c-a9a0-acd3-1f8e8c3b3263
* Content: [Troubleshooting content inspection errors - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-content-inspection#feedback)
* Content Source: [CloudAppSecurityDocs/troubleshooting-content-inspection.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/troubleshooting-content-inspection.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@gesmith-Ms Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@gesmith-Ms Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Since labels are not related to this troubleshooting guide, it was not added but can be seen in the following topic: [Azure Information Protection integration](https://docs.microsoft.com/cloud-app-security/azip-integration#automatically-label-files).

Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
