### ISSUE TITLE
New activity policy templates for Microsoft Teams

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/CloudAppSecurityDocs#239]
The Access level change (Teams) policy seems to have a wrong query. You don't get any matches when a team is changed to public. When you edit the policy and change the "Activity Object ID" to "item", matches are shown.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e4554f-32d3-6166-0fb4-f7382d063ef6
* Version Independent ID: de6a662e-0676-3e47-1321-5b6e14a54b14
* Content: [Create policies to control activities in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/user-activity-policies)
* Content Source: [CloudAppSecurityDocs/user-activity-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/user-activity-policies.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

However, I forwarded your observation to the product team who will look into the issue and, if relevant, issue a fix. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

Because this is not a documentation issue, I am closing this issue.

**Comment by shsagir** [comment]
@BakkerJan I heard back from the product team and a fix is being released in the coming weeks. Thanks again for reporting the issue.
