### ISSUE TITLE
Link to "Get started with Office 365 Cloud App Security"

### ISSUE THREAD

**Issue by ntw2** [MicrosoftDocs/CloudAppSecurityDocs#252]
The link to "Get started with Office 365 Cloud App Security" links to https://support.office.com/article/Get-started-with-Advanced-Management-Security-d9ee4d67-f2b3-42b4-9c9e-c4529904990a, which is titled "Quickstart: Get started with Microsoft Cloud App Security" and nowhere on that page is "Office 365 Cloud App Security" present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ntw2 Thanks for your feedback. After investigating, we've discovered the link is correct as the Get started topic covers Office 356 as well, and hence no change is required.

Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
