### ISSUE TITLE
Enabled this connector 3 months ago and it's still processing only 1-3 G Suite users a day

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/CloudAppSecurityDocs#258]
We have over 170,000 more users to go (215,000 processed), so what factors might speed up this process? When testing the connection via the "Test now" button it comes back after a few minutes with "Success"

The "Dashboard" "Activity log" and "Alerts" tabs for G Suite have zero data populated, which, after three months, doesn't sound right.

Are there logs on either the Google or Microsoft side that might tell us if we hit a limit, etc.?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18085b0-ca97-5623-fc42-5395acf55f1f
* Version Independent ID: 942d682c-a471-a8c9-e12f-cc7d4aafbad3
* Content: [Support and troubleshooting information for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/support-and-ts#feedback)
* Content Source: [CloudAppSecurityDocs/support-and-ts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/support-and-ts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft with feedback about our product documentation. As we understand it, you're describing an issue you are having with the product itself and not with the product documentation.

Your issue has been forwarded to the product team, but depending on the complexity of the issue, it could take from a few business days to a few weeks to look further into your issue. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

You can also get assistance or support for your product issue, by [opening a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

Because this issue does not relate to a documentation request, we are closing this issue.
