### ISSUE TITLE
Additional activity sources

### ISSUE THREAD

**Issue by kingwil** [MicrosoftDocs/CloudAppSecurityDocs#260]
Step 4 mentions Device tags, Location, IP address, User agent tag.. However, there are additional options such as user/group, Registered ISP.. Should the documentation be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e0921d-c905-8f46-403d-2e05e9645cb8
* Version Independent ID: af25066d-94c9-923d-0f65-36d834adcbc0
* Content: [Create Cloud App Security access policies to allow and block access](https://docs.microsoft.com/en-us/cloud-app-security/access-policy-aad)
* Content Source: [CloudAppSecurityDocs/access-policy-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/access-policy-aad.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@kingwil  Thanks for your feedback.

There are definitely more options available, however, the list is not mean to be exhaustive. Therefore, the step states "Filters include the following options", meaning includes but is not limited to. Hence, on this occasion, we don't think a change is required. But, thanks for making the suggestion.

Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
