### ISSUE TITLE
LogCollectorInstaller.ps1 script has incorrect URL to download WindowsDockerInstaller

### ISSUE THREAD

**Issue by CloudWizard3010** [MicrosoftDocs/CloudAppSecurityDocs#334]
[Enter feedback here]
The script LogCollectorInstaller.ps1 has incorrect URL to download WindowsDockerInstaller File. When the script tries to access the give URL - https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe, script throws Error - 403 Forbidden. When trying to access this same url via browser, i get Access Denied Html page.

Please correct the URL to download Docker setup for Windows in this script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by minasaneed** [comment]
> [Enter feedback here]
> The script LogCollectorInstaller.ps1 has incorrect URL to download WindowsDockerInstaller File. When the script tries to access the give URL - https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe, script throws Error - 403 Forbidden. When trying to access this same url via browser, i get Access Denied Html page.
> 
> Please correct the URL to download Docker setup for Windows in this script.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
> * Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
> * Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
> * Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
> * Service: **cloud-app-security**
> * Product: ****
> * Technology: ****
> * GitHub Login: @shsagir
> * Microsoft Alias: **shsagir**

Update the **logcollectorinstaller.ps1** in **line 62** with the below new **url** for docker in windows.

$DockerInstallerURL = "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe";

**Comment by shsagir** [comment]
@minasaneed Thanks for contacting Microsoft with feedback about our product documentation. As we understand it, you're describing an issue you are having with the product itself and not with the product documentation.

Your issue has been forwarded to the product team, but depending on the complexity of the issue, it could take from a few business days to a few weeks to look further into your issue. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

You can also get assistance or support for your product issue, by [opening a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

Because this issue does not relate to documentation a request, we are closing this issue.
