### ISSUE TITLE
Issue with MCASInstallDocker.sh on CentOS 8

### ISSUE THREAD

**Issue by k-e-v-i-n-c-o-s-t-e-r** [MicrosoftDocs/CloudAppSecurityDocs#341]
Deployment failing on following line, commenting out or removing fast resolves.

`yum makecache fast > /dev/null 2>&1 || exit_on_error "Failed adding repo"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload using on-premises Docker](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@k-e-v-i-n-c-o-s-t-e-r  Thanks for contacting Microsoft about your issue.

As we understand it, you're describing a problem with the product itself and not with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
