### ISSUE TITLE
Security of Url Suffix?

### ISSUE THREAD

**Issue by dsm0880** [MicrosoftDocs/CloudAppSecurityDocs#344]
Quick question, I'm not familiar with adding a suffix to a URL from a security perspective. I'm about to add this suffix to our CSP header policy but I wanted to pause and think through if this opens up a vulnerability. At the end of the day you are publicly calling this newly formed url in the form of *.cas.ms so you must own this domain? I'm just want to make sure nobody could easily spoof this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e092a97-a2c2-849c-6bd0-6e73a90ffc57
* Version Independent ID: 2eeaa902-7a79-5a32-0031-2290302a378f
* Content: [Troubleshooting - What is cas.ms, mcas.ms, or mcas-gov.us?](https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-proxy-url)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy-url.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/troubleshooting-proxy-url.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@dsm0880 Thanks for contacting Microsoft about your issue.

As we understand it, you're describing a question about the product itself and not with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
