### ISSUE TITLE
API to change custom tag of cloud apps in mcas

### ISSUE THREAD

**Issue by PawanGupta01** [MicrosoftDocs/CloudAppSecurityDocs#345]
Hi Team,

I have a requirement to change tags of various cloud applications from "None" to a custom app "ABC" (for example) at a time. If there is a API for the same, I can build a script?

Intro to tags- https://docs.microsoft.com/en-us/cloud-app-security/discovered-app-queries#creating-and-managing-custom-app-tags
Intro to API- https://docs.microsoft.com/en-us/cloud-app-security/api-introduction

**Comment by shsagir** [comment]
@PawanGupta01 Thanks for contacting Microsoft about your issue. I am not aware of an API to change the tags on apps, though it is possible to [create new IP ranges using the API](https://docs.microsoft.com/en-us/cloud-app-security/api-data-enrichment).

Since this is not a documentation issue, I am closing this issue. However, I suggest that you consider [opening a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [sending feedback](mailto:casfeedback@microsoft.com) so that we can look into your sugggestion.
