### ISSUE TITLE
Limiting the FTP port range rather than using 20000-20099

### ISSUE THREAD

**Issue by simonkw2000** [MicrosoftDocs/CloudAppSecurityDocs#346]
From the setup of the log collector using below as reference, it mentioned that the FTP ports shall be configured in 20000-20099. Can we limit the port range to **20000-20010**? Thanks.

https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu

**Example:**
(echo 6f19225ea69cf5f178139551986d3d797c92a5a43bef46469fcc997aec2ccc6f) | docker run --name MyLogCollector -p 21:21 -p 20000-20099:20000-20099 -e "PUBLICIP='192.2.2.2'" -e "PROXY=192.168.10.1:8080" -e "CONSOLE=tenant2.eu1-rs.adallom.com" -e "COLLECTOR=MyLogCollector" --security-opt apparmor:unconfined --cap-add=SYS_ADMIN --restart unless-stopped -a stdin -i microsoft/caslogcollector starter

**Comment by shsagir** [comment]
@simonkw2000 Thanks for contacting Microsoft about your question. If I understand your question correctly, you can change the port range with the `-p` switch, as follows: -p 20000-20010:20000-20010

If you need any further assistance, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.

As we understand it, you're describing a question about the product itself and not with the product documentation and hence we're closing this issue.
