### ISSUE TITLE
Significance vs Security configuration apps

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/CloudAppSecurityDocs#348]
What's the difference between this one and the Microsoft Azure that is in the **[Security configuration apps]** tab?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da9a9fad-ff34-4689-c30e-404a774f9bd3
* Version Independent ID: 351b6aa7-da8e-350d-c002-6e0689b350cc
* Content: [Connect Azure to Cloud App Security](https://docs.microsoft.com/en-gb/cloud-app-security/connect-azure-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-azure-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-azure-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@icelava Thanks for contacting Microsoft about your issue.

As we understand it, you're asking about a feature comparison between products and not a problem with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
