### ISSUE TITLE
Missing Prerequisite

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#353]
An organization needs to have a firewall in order to upload logs. Cloud app discovery does not work for orgs that are totally in the cloud. Please make this clear in the prerequisites. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security#step-1-set-instant-visibility-protection-and-governance-actions-for-your-apps)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. After investigating, we've discovered that firewalls and proxies are not a prerequisite for Cloud Discovery. For instance, Cloud Discovery uses its native integration with Microsoft Defender for Endpoints for discovery. Therefore, we respectfully decline to make this change. But, thanks again; we always appreciate feedback on our documentation.

Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.

**Comment by DeanGross** [comment]
Ok, that's a fair point, but Defender for Endpoint is not listed as a prerequisite, please add this.
