### ISSUE TITLE
Missing Prerequisites

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#354]
Please add something about needing a firewall or proxy. Companies that are in the cloud don't have these and therefore cannot using Cloud App Discovery. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security#prerequisites)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. After investigating, we've discovered that firewalls and proxies are not a prerequisite for Cloud Discovery. For instance, Cloud Discovery uses its native integration with Microsoft Defender for Endpoints for discovery. Therefore, we respectfully decline to make this change. But, thanks again; we always appreciate feedback on our documentation.

Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
