### ISSUE TITLE
Screenshot includes typo

### ISSUE THREAD

**Issue by doctormay6** [MicrosoftDocs/CloudAppSecurityDocs#357]
The screenshot under step 2 in the section titled "Integrating with Azure Sentinel" has a typo in the drop down menu. The Generic SIEM option reads, "Integrate with _you_ SIEM server" rather than "Integrate with _your_ SIEM server". We have already integrated Azure Sentinel, so I no longer see this same drop down to see if the typo also still exists in the menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7baccc9-aded-5134-33bf-bdd20ca52637
* Version Independent ID: 2c646a17-0782-0352-ced5-822354a68271
* Content: [Azure Sentinel integration with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/siem-sentinel)
* Content Source: [CloudAppSecurityDocs/siem-sentinel.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/siem-sentinel.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by doctormay6** [comment]
![image](https://user-images.githubusercontent.com/24688343/105532537-947ab000-5cb0-11eb-9a7d-0eb7dd757c2e.png)
Here is an screenshot of the image I'm referring to.

**Comment by shsagir** [comment]
@doctormay6 Thanks for contacting Microsoft about your issue.

As we understand it, you're describing a problem with the product itself and not with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
