### ISSUE TITLE
User monitoring page is not appearing when using Internet Explore  

### ISSUE THREAD

**Issue by Ronnie995** [MicrosoftDocs/CloudAppSecurityDocs#359]
I have set up a monitoring page for uses when they login to an app that is currently part of Conditional APP access applications.  The monitoring page appears if the user is using Firefox or  Chrome, but it does not appear when the user is using IE.  It doe snot even appear to be using conditional app access at all.

**Comment by shsagir** [comment]
@Ronnie995 Thanks for contacting Microsoft about your issue.

As we understand it, you're describing a problem with the product itself and not with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
