### ISSUE TITLE
Concerns regarding requested permissions

### ISSUE THREAD

**Issue by MartinRapa** [MicrosoftDocs/CloudAppSecurityDocs#365]
Hi, 

I'm wondering why  this container needs '--security-opt apparmor:unconfined --cap-add=SYS_ADMIN'
Seems excesive for event forwarding and didn't found additional documentation.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818cbf6b-c397-8c86-e061-8e940ee94278
* Version Independent ID: 53b66b18-5321-b63e-a57b-44f146ff6944
* Content: [Configure automatic log upload using Docker in Azure](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure?tabs=centos)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@MartinRapa Thanks for contacting Microsoft about your query.

As we understand it, you're describing a question with the product itself and not with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
