### ISSUE TITLE
Extremely confusing names and sites for beginners

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/CloudAppSecurityDocs#386]
[Enter feedback here]
**Cloud App and Security, which portal? I'm new to this world and I already hate it!** Please add links to those fancy names as I am confused as hell

Here is a text file I generated to clear up the confusion as the docs say NOTHING where to connect to rather than just a long names that can mean anything, everything and nothing at the same time

1. **Microsoft 365 admin center** is admin.microsoft.com
2. **Microsoft 365 security center** is security.microsoft.com
3. **Office 365 Security & Compliance** protection.office.com
....... Hang on a sec, what is the difference between Microsoft 365 and Office 365?
4. **Microsoft 365 compliance center** compliance.microsoft.com
....... So Microsoft 365 Security and Compliance is different from Microsoft 365 compliance center?
5. **Microsoft Defender Security Center** securitycenter.windows.com which was renamed to **Microsoft Defender for Endpoint** which takes you to security.microsoft.com which is now **Microsoft 365 security center** As clear as mud!
6. **Microsoft Azure** portal.azure.com
7. **Microsoft Endpoint Manager admin center (Intune)** endpoint.microsoft.com
8. **Microsoft Defender for Identity** CompanyName.atp.azure.com
9. **Cloud App Security Portal** CompanyName.portal.cloudappsecurity.com
10. **Exchange admin center** outlook.office365.com (yep, because Exchange is Outlook and it is inside the Office domain, makes no sense at all!
11. **SharePoint Admin center** is YourCompany-admin.sharepoint.com
12. **Teams Admin Center** admin.teams.microsoft.com

_Come on Microsoft! Want to attract people to this platform? Then keep things simple! This is really confusing!_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fbda4c0-2222-b67a-615e-261fea7f3f05
* Version Independent ID: 13241ed3-46e9-5821-4760-4bdb9564c69e
* Content: [Working with discovered apps in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovered-apps)
* Content Source: [CloudAppSecurityDocs/discovered-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovered-apps.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment, We will investigate and get back to you.

**Comment by dcurwin** [comment]
@Anoni-Mouse - I really appreciate your feedback here. I know that since the products you mentioned are constantly being improved and updated, there can be confusion about the names and links for each of that. That can be certainly frustrating for new users of the product, and we certainly want to make the process for people like you, who are beginning to use them, as smoothly as possible.

I looked at your really helpful list, and reviewed Cloud App Security documentation (for which I'm responsible), and added quite a few links to the relevant portals or other sites when they're mentioned. I can't change the names of the products and services, but I can modify the documentation to make it as clear as possible where to go.

Please feel free to let me know if you see any pages in the Cloud App Security documentation that could use updating for clarity in this regard. I'll leave this issue open for now, and wait for your additional feedback. Thanks!

**Comment by Anoni-Mouse** [comment]
You guys rock! Thanks for making it more simple for beginners
________________________________

**Comment by dcurwin** [comment]
We're always happy to help! 

If it's ok with you, I'll close this GitHub issue, but feel free to open a new one any time you see pages where we could improve clarity.

**Comment by Anoni-Mouse** [comment]
Yes you can close the request. Thanks a ton
________________________________
