### ISSUE TITLE
Stream support for MCAS

### ISSUE THREAD

**Issue by jorge-ataide** [MicrosoftDocs/CloudAppSecurityDocs#390]
In the list of supported Office 365 apps, Stream is not showing.

But, right below in the Notes Stream is mentioned as a supported application, as we can see:

> receives all audited events from all supported services, such as PowerApps, Forms, Sway, and **Stream**.

In a test environment, even though Office 365 is connected as per documents, Stream logs do not appear in MCAS.

After all, is Stream supported or not?

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@jorge-ataide  - Thank you again for raising this issue. We've updated the document to avoid the confusion. MCAS shows all the activities being audited in O365, but the list does not call out Stream explicitly, since we don't mention every O365 activity and app.

If the Stream activity is not showing in MCAS, please raise a support ticket.
