### ISSUE TITLE
Bad docs

### ISSUE THREAD

**Issue by wesleykirkland** [MicrosoftDocs/CloudAppSecurityDocs#40]
It is never mentioned on how to deploy the appliance, you go to Azure and appear to deploy the "Azure AD Cloud App Discovery" appliance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2005aabb-11c8-3ab9-6e87-94b0ef5164be
* Version Independent ID: 0878ecbe-fcd1-eb38-8ddb-4b4ea685d3c0
* Content: [Deploy Cloud Discovery with Microsoft Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/set-up-cloud-discovery)
* Content Source: [CloudAppSecurityDocs/set-up-cloud-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/set-up-cloud-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi Wesley, I'm sorry this was unclear. Cloud App Security is a cloud service, so there isn't a physical app that needs to be deployed. In order to use Cloud Discovery, you can [upload logs manually](https://docs.microsoft.com/cloud-app-security/create-snapshot-cloud-discovery-reports) (which gives you a snapshot report based on the uploaded log) or [configure automatic log upload](https://docs.microsoft.com/cloud-app-security/discovery-docker) (which enables you to generate reports continuously, based on the data detected in the log collectors you connect to Cloud App Security). I can change the name of the article to Set up, rather than Deploy - I hope that helps. Thanks for your feedback!
