### ISSUE TITLE
Products supported in MCAS are not clear in specification on site

### ISSUE THREAD

**Issue by Scurry-DLG** [MicrosoftDocs/CloudAppSecurityDocs#426]
The products listed in the article are umbrella products (like office). We want to rollout apps to our end users but I need to know they are explicitly protected by MCAS before I roll them out. These are for the web versions and the products I would like clarification on are:

- Visio Web
- Project Web
- Planner
- Whiteboard (If I load attachments)
- Forms
- OneNote
- Lists
- Office (are all products covered? the office suite entails Publisher and Access and so on..)
- Power Platform in general

Could you please add a product specific list as we cannot use the service without knowing it is supported. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c7ec0b-8a9e-1aec-f8a6-97864b401aef
* Version Independent ID: dc977df5-36a8-0371-c7fa-8f745df452ba
* Content: [Connect Office 365 to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-office-365-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-office-365-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-office-365-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@Scurry-DLG - Thanks again for your question. After investigating the issue, we can now share the that the official list of supported services is here:

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#microsoft-365-services-that-support-auditing

We've updated the MCAS documents to link to that page instead of providing a partial list of supported services. Please check that page for information about which services provide the required logs that MCAS uses.

**Comment by Scurry-DLG** [comment]
Thank you for the assistance but that would imply  word/excel/powerpoint/oulook/Project/Visio are not included or is there another list to append?

Stephen

**Comment by dcurwin** [comment]
@idbasre @markjjo  - Any thoughts on this?
