### ISSUE TITLE
Clarification of MDE License

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#497]
Does this require Defender for Endpoint P1 or P2 license? Please clarify
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Defender for Cloud Apps](https://docs.microsoft.com/en-us/cloud-app-security/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mde-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@DeanGross  -  This issue is being investigated and there are already two other GitHub issues regarding it:

https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/496

https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/492

So I'm going to close this issue, but you're welcome to follow those to keep track of our progress, which will hopefully be coming soon.

**Comment by dcurwin** [comment]
@DeanGross 
Sorry for the delay in the response. We've clarified with the product teams and a Plan 2 license is required.
