### ISSUE TITLE
Behaviour of thottling needs to be documented

### ISSUE THREAD

**Issue by snowch** [MicrosoftDocs/CloudAppSecurityDocs#628]
This page has a note stating that the requests will be throttled:

> Note
> 
> If no limit is provided, a default of 100 will be set.
> Responses for all requests made with the API token are limited to a maximum of 100 items.
> The throttle limit for all API requests is 30 requests per minute per tenant.

Documentation is needed to describe how this has been implemented so that clients can be coded appropriately.  Does the API return a `HTTP 429 Too Many Requests` response when the rate limit has been exceeded or does it follow a different strategy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7176c15a-025f-f67a-502c-5353eced167f
* Version Independent ID: ec00e101-7d22-d7b6-f6a7-1fc2208eb69a
* Content: [REST API - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/api-introduction#limits)
* Content Source: [CloudAppSecurityDocs/api-introduction.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-introduction.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by snowch** [comment]
Thanks @dcurwin.

I found this [page](https://learn.microsoft.com/en-us/partner-center/developer/api-throttling-guidance) for the partner center.  That's the type of documentation I'm looking for.

**Comment by batamig** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. 

The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. 

#please-close
