### ISSUE TITLE
Third party dlp REQMOD block response format

### ISSUE THREAD

**Issue by wazhar** [MicrosoftDocs/CloudAppSecurityDocs#67]
Hi,

This document discusses Forcepoint and Symantec DLP integration, how about generic DLP integration REQMOD ? What kind of ICAP server response is required to indicate  HTTP/HTTPS Block ? It would be of great help if Allow and Block ICAP responses could be documented here . 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7311538-fd31-674c-7fb1-430eb07406fe
* Version Independent ID: ab868458-d2b4-57bb-14b6-b44fd6a3f958
* Content: [Cloud App Security external DLP integration over secure ICAP](https://docs.microsoft.com/en-us/cloud-app-security/icap-stunnel)
* Content Source: [CloudAppSecurityDocs/icap-stunnel.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/icap-stunnel.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by wazhar** [comment]
The document talks about verdict: allowed/blocked does this mean CAS requires 3rd party ICAP server to produce verdict header which either sets blocked or allowed value. 

[https://docs.microsoft.com/en-us/cloud-app-security/icap-stunnel](url)

Something like this ?? :
ICAP/1.0 200 OK
verdict: blocked
Encapsulated: null-body=0

**Comment by rkarlin** [comment]
Hi Wasim,
thanks so much for reaching out. I agree that the language we used makes it sound confusing. I'll publish a fix with our next update! Thanks again for your contribution!

**Comment by wazhar** [comment]
> Hi Wasim,
> thanks so much for reaching out. I agree that the language we used makes it sound confusing. I'll publish a fix with our next update! Thanks again for your contribution!

When is the next update planned ?

**Comment by rkarlin** [comment]
Hi @wazhar , ordinarily we publish bi-weekly. You should already see this change.

**Comment by wazhar** [comment]
@rkarlin I don't see any change.  [External DLP Integration](https://docs.microsoft.com/en-us/cloud-app-security/icap-stunnel)

Page timestamp says it was last updated '04/22/2018'.

**Comment by msmbaldwin** [comment]
This fix has been live for some time.

**Comment by wazhar** [comment]
@msmbaldwin 
I still don't see this document explaining generic REQMOD allow/block verdict. 

Here is the response that I got when I posted the same question at casfeedback@microsoft.com
> For all generic ICAP servers we can enable a configuration which requires the server to send the status code 200 in order to identify a match. In such cases the verdict doesn’t matter as long as the status code is present (200 – match, 204 – no match). 

However for this to work, there is some configuration that has to be enabled for the tenant. I had to provide my tenant id to the CAS team for this reason. It worked after that. 

You might want to verify and document this. 

Thanks.

**Comment by ladybonner** [comment]
If it needs to be dead and not live...then kill it!
-------- Original message --------From: "M. Baldwin" <notifications@github.com> Date: 2/4/19  2:58 PM  (GMT-06:00) To: MicrosoftDocs/CloudAppSecurityDocs <CloudAppSecurityDocs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [MicrosoftDocs/CloudAppSecurityDocs] Third party dlp REQMOD block
  response format (#67) 
This fix has been live for some time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/CloudAppSecurityDocs","title":"MicrosoftDocs/CloudAppSecurityDocs","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@msmbaldwin in #67: This fix has been live for some time. "}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/67#issuecomment-460410478"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/67#issuecomment-460410478",
"url": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/67#issuecomment-460410478",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
