### ISSUE TITLE
Import Users from Connected Apps does not show all groups

### ISSUE THREAD

**Issue by MgramTheDuck** [MicrosoftDocs/CloudAppSecurityDocs#678]
[Defender for cloud apps docs](https://learn.microsoft.com/en-us/defender-cloud-apps/user-groups) explains that "You can import any group from your connected apps" however when using the UI to import a security group from Office 365 (Azure AD) it only shows the first 50 or so groups in the UI, you cannot manually add other groups. 

The list of groups stops alphabetically after about C-D. No further groups are shown in the list. 

![image](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/assets/85346345/c7a31561-f3cd-47c0-a3c8-02993b0af07a)

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
I'm tagging @LeorHurwitz on this issue for tracking. Thanks!

**Comment by batamig** [comment]
Hi @MgramTheDuck, thanks again for writing into docs. 
This is an autocomplete component that works as described by design - we return the first 50 groups, but you can search for other groups by entering text in the search bar. 

We'll update the docs to explain this better, but please advise whether this helps you or not. 
If, after searching for your group, you still can't find it, please contact support to help you with your specific use case. 

We appreciate your contribution!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
