### ISSUE TITLE
API Name When Granting Permission on App is misleading

### ISSUE THREAD

**Issue by lmahoney1** [MicrosoftDocs/CloudAppSecurityDocs#682]
In bullet point 4 of section `Create an app` the instructions say to type `Microsoft Cloud App Security` when typing in the API to give permissions to. There is also a 'note' blurb stating:

> Microsoft Cloud App Security does not appear in the original list. Start writing its name in the text box to see it appear. Make sure to type this name, even though the product is now called Defender for Cloud Apps.

However, the screenshot shown directly after the instructions and blurb show the user typing in 'Defender for Cloud Apps'.

I feel this is slightly confusing. I'm assuming `Microsoft Cloud App Security` should be used, but the discrepancy prevents me from being fully confident.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3528aed5-52df-23fe-ad48-d36403fba571
* Version Independent ID: 3528aed5-52df-23fe-ad48-d36403fba571
* Content: [Access with application context - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/api-authentication-application#create-an-app)
* Content Source: [CloudAppSecurityDocs/api-authentication-application.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-authentication-application.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Thanks for your dedication to our documentation. 

Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. 

The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. 

We are closing this issue for now, but feel free to comment here as necessary. #please-close
