### ISSUE TITLE
Defender Portal OAuth apps tab moved?

### ISSUE THREAD

**Issue by ucgeek** [MicrosoftDocs/CloudAppSecurityDocs#697]
[Enter feedback here]
I am no longer seeing -> "In the Microsoft Defender Portal, under Cloud Apps select OAuth apps."

OAuth apps has disappeared at least from my tenant. Does docs need updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3543307c-9c07-720c-e4fe-3aa6cb43f680
* Version Independent ID: df363f37-c41a-7493-6573-c7a8f4ff1aaf
* Content: [Manage OAuth apps - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/manage-app-permissions)
* Content Source: [CloudAppSecurityDocs/manage-app-permissions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/manage-app-permissions.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ucgeek, thanks for writing into docs. If you don't see the OAuth apps page, please check for your apps on the App Governance page. For more information, see [View your app details with app governance](https://learn.microsoft.com/en-us/defender-cloud-apps/app-governance-visibility-insights-view-apps).

We'll check into the documentation to see what needs to be updated. We appreciate your feedback!

**Comment by ucgeek** [comment]
This is all I see - no OAuth apps or App Governance: 
![image](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/assets/39198233/8f3036cb-6288-4990-a665-4bdc1b746b44)

**Comment by batamig** [comment]
Hi @ucgeek, in this case, it might be a permissions issue. You can see the roles required for app governance here:
[Turn on app governance for Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/app-governance-get-started#roles).

If you don't have app governance turned on, I suggest that you open a support ticket so that the support team can help understand your specific scenario.

**Comment by batamig** [comment]
hi @ucgeek, we've updated this page to clarify issues for when users have preview features and App governance turned on.
However, this may not be relevant if your issue is related to permissions. 
I'm closing this issue for now, but feel free to continue commenting if you have more feedback on the docs.

We appreciate your contribution! 
#please-close
