### ISSUE TITLE
[QUESTION][Entities][FILTER BY USER]

### ISSUE THREAD

**Issue by brunorafaeli** [MicrosoftDocs/CloudAppSecurityDocs#734]
### Overview
Is it possible to filter only entities that are Users? If so, how do we do this? The documentation is not clear about the Entity schema.

**Endpoint:** `/api/v1/entities/`
**Ref:** https://learn.microsoft.com/en-us/defender-cloud-apps/api-entities-list

Thanks :)

**Comment by batamig** [comment]
@Mravela, can you advise about this issue or tag someone who can? thanks!

**Comment by brunorafaeli** [comment]
@Mravela, I appreciate it if you could support us on this question.

**Comment by Mravela** [comment]
Hi,
I can check with engineering folks. They are not available here to tag.

**Comment by brunorafaeli** [comment]
Hey @Mravela any response from engineering?

**Comment by Mravela** [comment]
Hi @Bruno ***@***.***>,
I was OOF last week and resumed work today
Let me get back to you by mi next-week.

**Comment by batamig** [comment]
Hi @brunorafaeli, 

Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response.
Since this is more of a product question, we also recommend that you ask in our [Defender for Cloud Apps Tech Community](https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/bd-p/MicrosoftDefenderCloudApps), where there are experts available to help. 
If the discussion there indicates that we need a docs update, the team will make sure to open a work item for our backlog.

I'm going to close this issue for now. We appreciate your contribution and encourage you to submit further docs feedback through our updated control at the top of the page as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

#please-close
