### ISSUE TITLE
Need Detail on Security Role to Deanonymize data

### ISSUE THREAD

**Issue by sliver85** [MicrosoftDocs/CloudAppSecurityDocs#737]
This page should include detail on the security role/permissions required to deanonymize data. We've found that "security operators" cannot do this, while "security administrators" can. It is really helpful when the documentation lists the specific roles, either global M365 roles or MDfCA roles, can perform the documented actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19faaa3d-f160-361c-406b-b257498224e1
* Version Independent ID: 2c9d8c98-c043-b73b-d54e-98f9cfbd6e4e
* Content: [Cloud Discovery data anonymization - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/cloud-discovery-anonymizer)
* Content Source: [CloudAppSecurityDocs/cloud-discovery-anonymizer.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/cloud-discovery-anonymizer.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @silver85, thanks for writing into docs! In general, our role information is listed [here](https://learn.microsoft.com/en-us/defender-cloud-apps/manage-admins), but we'll investigate this point and consider an update to this page.

**Comment by batamig** [comment]
Thanks for your dedication to our documentation. 

Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. 

We are closing this issue for now, but feel free to comment here as necessary. #please-close
