### ISSUE TITLE
What is a Microsoft Defender for Microsoft 365 P1 ?

### ISSUE THREAD

**Issue by swiftsolves-msft** [MicrosoftDocs/CloudAppSecurityDocs#742]
Documentation states a required license _"for requires a valid license for Microsoft Defender for Microsoft 365 P1"_ Does this need to be cleaned up, Defender for Office 365 P1 instead ?

**Comment by batamig** [comment]
Hi @swiftsolves-msft, thanks for writing into docs! I don't see this string in our docs, and this GitHub issue doesn't have a link to a specific page. 
Since you're internal to Microsoft, I'm going to close this GitHub issue and recommend that you contact use internally to clarify. 

Looking forward to hearing from you!
#please-close
