### ISSUE TITLE
Removing applications from Conditional Access App Control apps

### ISSUE THREAD

**Issue by msandbu** [MicrosoftDocs/CloudAppSecurityDocs#85]
I don't see to have an option to remove applications from Conditional Access App Control apps? is this possible if not it should be reflected in the docs.

**Comment by rkarlin** [comment]
Hi @msandbu thanks so much for reaching out. I am checking into this and will get back to you.

**Comment by rkarlin** [comment]
Hi @msandbu , apps can be removed from a policy so that they do not apply. You can’t remove an app, once onboarded, from the “Conditional Access App Control apps” page, but that doesn’t change any behavior for the app as long as none of the policies enforce any actions on it. I'll make sure that's clear in the article.

**Comment by rkarlin** [comment]
#please-close @msmbaldwin
