### ISSUE TITLE
user enrichment user duplication

### ISSUE THREAD

**Issue by mekkimuyeeb** [MicrosoftDocs/CloudAppSecurityDocs#90]
The documentation states that enabling user enrichment might result in user duplication. Is there a way to identify if this will occur, is there away to fix it if it does occur and is there a work around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1ddbec-2517-6111-942c-305df8b725f8
* Version Independent ID: 4565cf20-c44b-d79b-73e1-327049687db3
* Content: [Enrich Cloud App Security Discovery data with Azure AD usernames](https://docs.microsoft.com/en-us/cloud-app-security/cloud-discovery-aad-enrichment)
* Content Source: [CloudAppSecurityDocs/cloud-discovery-aad-enrichment.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/cloud-discovery-aad-enrichment.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mekkimuyeeb** [comment]
Thank you. This helps a lot

**Comment by rkarlin** [comment]
#please-close 
@msmbaldwin

**Comment by ladybonner** [comment]
Well, there sure are several numbers closing!!!
-------- Original message --------From: "M. Baldwin" <notifications@github.com> Date: 2/4/19  3:00 PM  (GMT-06:00) To: MicrosoftDocs/CloudAppSecurityDocs <CloudAppSecurityDocs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [MicrosoftDocs/CloudAppSecurityDocs] user enrichment user
  duplication (#90) 
Closed #90.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/CloudAppSecurityDocs","title":"MicrosoftDocs/CloudAppSecurityDocs","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #90."}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/90#event-2116852841"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/90#event-2116852841",
"url": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/90#event-2116852841",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
