### ISSUE TITLE
Very excited

### ISSUE THREAD

**Issue by OliJon77** [MicrosoftDocs/CloudAppSecurityDocs#93]
Awesome

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0135a54e-8e51-87ed-2d33-58425fa5070f
* Version Independent ID: 5cdd0558-5ee5-b1cc-e47d-a4aa5bd6f274
* Content: [Working with the Cloud App Security dashboard](https://docs.microsoft.com/en-us/cloud-app-security/daily-activities-to-protect-your-cloud-environment)
* Content Source: [CloudAppSecurityDocs/daily-activities-to-protect-your-cloud-environment.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/daily-activities-to-protect-your-cloud-environment.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by msmbaldwin** [comment]
#please-close

**Comment by ladybonner** [comment]
What needs to be closed?
-------- Original message --------From: "M. Baldwin" <notifications@github.com> Date: 2/4/19  3:11 PM  (GMT-06:00) To: MicrosoftDocs/CloudAppSecurityDocs <CloudAppSecurityDocs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [MicrosoftDocs/CloudAppSecurityDocs] Very excited (#93) 
#please-close

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/CloudAppSecurityDocs","title":"MicrosoftDocs/CloudAppSecurityDocs","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@msmbaldwin in #93: #please-close"}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/93#issuecomment-460414291"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/93#issuecomment-460414291",
"url": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/93#issuecomment-460414291",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ladybonner** [comment]
Well, I am very glad that someone is excited!!
-------- Original message --------From: "M. Baldwin" <notifications@github.com> Date: 2/4/19  3:00 PM  (GMT-06:00) To: MicrosoftDocs/CloudAppSecurityDocs <CloudAppSecurityDocs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [MicrosoftDocs/CloudAppSecurityDocs] Very excited (#93) 
Closed #93.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/CloudAppSecurityDocs","title":"MicrosoftDocs/CloudAppSecurityDocs","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #93."}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/93#event-2116853435"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/93#event-2116853435",
"url": "https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/93#event-2116853435",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
